### PR TITLE
Feature Addition: Reverse Option

### PR DESCRIPTION
**Pull request by djosh34**
Hey mlange-42,

Just wanted to drop in a pull request for something you might find a bit hacky, but I found myself needing a reverse option. The approach here is a bit unconventional – instead of overhauling the code, I went for reversing the text_lines and grid. To tackle the issue of characters facing the wrong direction, I flipped them (so a 'left-up' becomes 'left-down', and so on).

It might be more ideal to adjust how the Character struct is accessed with the reverse option in mind, but that would require a significant refactor of the existing code. From what I've tested, it looks like it works pretty well across different character sets. Would love to hear your thoughts on this and if it's something you'd consider merging.

Cheers!

### CODE REVIEW

**Comment by mlange-42** [comment]
Hi @djosh34,
thank you for this PR! I am totally ok with this solution, given how simple and effective it is compared to the alternatives.

Will give it a try as soon as I can. Meanwhile, please fix the linter error.

**Comment by djosh34** [comment]
@mlange-42 Cargo clippy gave another warning about elided lifetimes. Was it suppose to stay there? In the second commit is still took it away to make clippy happy, but I'm not sure if that is what you want

**Comment by mlange-42** [comment]
It was the failed `fmt` check that I meant. It did not even proceed to clippy. The lifetime thing is a change to clippy, introduced after the last run of the CI. So Rust has become smarter there. So it is fine that you fixed it.

**Comment by djosh34** [comment]
Yes I forgot to mention that I indeed also did a `fmt`

**Comment by djosh34** [comment]
Dear @mlange-42,

I have addressed all fmt errors, and GitHub confirms the pull request is ready for merging. I understand you could have a busy schedule, but if possible, could you please test the feature and proceed with the merge? It would be greatly appreciated.

Thank you.

Best regards

**Comment by mlange-42** [comment]
@djosh34 Sorry, this slipped through...

**Pull request merged**
